@startuml

  [*] --> TURNED_OFF
  TURNED_OFF --> TURNED_ON : PUSH_TURN_ON

  TURNED_ON --> CHECKED_RESOURCES : CHECK_RESOURCES
  TURNED_ON --> TURNED_OFF : PUSH_TURN_OFF

  CHECKED_RESOURCES --> STARTED_BREW : PUSH_START_BREW
  CHECKED_RESOURCES --> TURNED_OFF : PUSH_TURN_OFF

  STARTED_BREW --> DONE : BREW
  DONE --> CHECKED_RESOURCES : CHECK_RESOURCES
  DONE --> TURNED_OFF : PUSH_TURN_OFF

@enduml